local-phone-apps = AppSharing \
                   BackupRestoreConfirmation \
		   Bluetooth \
		   BrcmBluetoothServices \
                   Camera \
                   CertInstaller \
		   CIMETPCHS \
		   CIMETPCHT \
                   CustomizationSettingsProvider \
                   DefaultContainerService \
                   DemoFLOPackageInstaller \
                   DLNAMiddleLayer \
                   DrmProvider \
                   FilePicker \
                   Flashlight \
                   FM_Radio \
                   FMRadioService \
                   GoogleTTS \
                   HTCAlbum \
                   HtcBeatsNotify \
                   HtcDMC \
                   HTC_IME \
                   HtcMediaUploader \
                   HtcMusic \
                   HtcMusicEnhancer \
                   HtcPhotoEnhancer \
                   HtcSoundEnhancerSetting \
                   HtcVideoPlayer \
                   HTMLViewer \
                   IMEHWRPenPower \
                   IMEXT9English \
                   KeyChain \
                   LMW \
                   MediaProvider \
                   PhaseBeam \
                   PluginManager \
                   SDCardWizard \
                   SettingsProvider \
                   SharedStorageBackup \
                   TrimIt \
                   Usage \
                   VenomTweaks \
                   WifiRouter
