#!/system/bin/sh
# ===========================================================================
#  Virtuous ROM Tools (rmk)
#
#  Tue Jun  7 13:57:52 PDT 2011
#
#  With rmk permission to use with RuiZhe Rom Gfan
# ===========================================================================

# Check whether any cpu tuning apps are already installed.
# If not, we'll start our custom daemon.

if [ ! -e /data/system/packages.xml ] ; then
/system/xbin/virtuous_oc
	exit 0
else
if /system/xbin/busybox grep -q "ch.amana.android.cputuner" /data/system/packages.xml ; then
	exit 0
fi
if /system/xbin/busybox grep -q "com.mhuang.overclocking" /data/system/packages.xml ; then
	exit 0
fi
if /system/xbin/busybox grep -q "org.freecoder.widgets.overclock" /data/system/packages.xml ; then
	exit 0
fi
if /system/xbin/busybox grep -q "com.antutu.CpuMasterFree" /data/system/packages.xml ; then
	exit 0
fi
/system/xbin/virtuous_oc
fi

